spring:
  profiles:
    active: aws


---
spring:
  profiles: local

  datasource:
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

---
spring:
  profiles: aws

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    url: jdbc:mysql://localhost:3306/yhkdb?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false

    username: root
    password: qwer12#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update

